import React, { useState, useEffect } from 'react';
import { 
  FileText, Sparkles, Download, Upload, RefreshCw, Check, 
  Settings, Type, Layout, Eye, Copy, ArrowRight, ShieldCheck, 
  FileCode, Layers, File, Edit3, HelpCircle, CheckCircle2
} from 'lucide-react';
import toast from 'react-hot-toast';
import PageContainer from '../../components/common/PageContainer';
import { documentService } from '../../services/documentService';

export const DocumentGenerator = () => {
  const [content, setContent] = useState(
    `# Executive Strategy Report 2026\n\n## Overview\nTaskPilot AI Document Generator Agent transforms raw text into highly structured, formatted PDF and Word documents.\n\n## Key Deliverables\n- **Multi-Format Support**: Generate PDF (.pdf) and Microsoft Word (.docx).\n- **Gemini 2.5 Flash Integration**: Optional AI content enhancement for grammar, professional tone, and report structuring.\n- **Real-Time Live Preview**: Instant visual rendering of document headers, footers, and typography.\n\n## Conclusion\nAll document binaries are generated locally with full metadata embedding.`
  );

  const [title, setTitle] = useState('Executive Strategy Report 2026');
  const [author, setAuthor] = useState('TaskPilot AI Candidate');
  const [subject, setSubject] = useState('Business Architecture');
  const [keywords, setKeywords] = useState('AI, Document, Strategy');

  // Styling Settings
  const [fontFamily, setFontFamily] = useState('Helvetica');
  const [fontSize, setFontSize] = useState(12);
  const [pageSize, setPageSize] = useState('A4');
  const [orientation, setOrientation] = useState('portrait');
  const [margins, setMargins] = useState('normal');
  const [headerText, setHeaderText] = useState('TaskPilot AI Enterprise Docs');
  const [footerText, setFooterText] = useState('Generated by TaskPilot AI Document Generator');
  const [includePageNumbers, setIncludePageNumbers] = useState(true);

  // Selected Formats & Enhancements
  const [selectedFormats, setSelectedFormats] = useState({ pdf: true, docx: true });
  const [selectedEnhancement, setSelectedEnhancement] = useState(null);

  // Processing States
  const [isEnhancing, setIsEnhancing] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedResult, setGeneratedResult] = useState(null);
  const [activeTab, setActiveTab] = useState('editor'); // 'editor' | 'preview'

  const enhancementOptions = [
    { id: 'grammar', label: 'Improve Grammar', desc: 'Fix spelling, punctuation & syntax' },
    { id: 'rewrite', label: 'Professional Rewrite', desc: 'Sleek executive corporate phrasing' },
    { id: 'summarize', label: 'Summarize', desc: 'Key bullet points & executive summary' },
    { id: 'expand', label: 'Expand Content', desc: 'Add detailed technical context' },
    { id: 'formal', label: 'Formal Tone', desc: 'Authoritative business language' },
    { id: 'friendly', label: 'Friendly Tone', desc: 'Warm and approachable wording' },
    { id: 'business_letter', label: 'Business Letter', desc: 'Formal salutation & sign-off layout' },
    { id: 'meeting_minutes', label: 'Meeting Minutes', desc: 'Attendees, agenda & action items' },
    { id: 'technical_doc', label: 'Technical Documentation', desc: 'Overview, specs & architecture' },
    { id: 'academic_report', label: 'Academic Report', desc: 'Abstract, methodology & findings' },
    { id: 'resume', label: 'Resume Format', desc: 'Summary, skills & experience' },
    { id: 'report', label: 'Convert into Report', desc: 'Full executive report structure' }
  ];

  const handleFileUpload = (e) => {
    const file = e.target.files[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      const fileText = event.target.result;
      setContent(fileText);
      if (!title || title === 'Untitled Document') {
        setTitle(file.name.replace(/\.[^/.]+$/, ''));
      }
      toast.success(`Loaded file: ${file.name}`);
    };
    reader.readAsText(file);
  };

  const handleEnhanceWithGemini = async (type) => {
    if (!content || content.trim() === '') {
      toast.error('Please enter or upload text before applying AI enhancement.');
      return;
    }

    setSelectedEnhancement(type);
    setIsEnhancing(true);
    const toastId = toast.loading(`Enhancing content with Gemini 2.5 Flash (${type})...`);

    try {
      const enhancedText = await documentService.enhanceContent(content, type);
      setContent(enhancedText);
      toast.success('AI Content Enhancement applied!', { id: toastId });
    } catch (error) {
      toast.error('AI Enhancement failed. Retaining original text.', { id: toastId });
    } finally {
      setIsEnhancing(false);
    }
  };

  const handleGenerateDocuments = async () => {
    if (!content || content.trim() === '') {
      toast.error('Document content cannot be empty.');
      return;
    }

    setIsGenerating(true);
    const toastId = toast.loading('Generating formatted PDF and Word (.docx) documents...');

    try {
      const payload = {
        title,
        author,
        subject,
        keywords,
        content,
        fontFamily,
        fontSize,
        pageSize,
        orientation,
        margins,
        headerText,
        footerText,
        includePageNumbers,
        enhancementType: selectedEnhancement
      };

      const result = await documentService.generateAll(payload);
      setGeneratedResult(result);
      setActiveTab('preview');
      toast.success('Document generated successfully!', { id: toastId });
    } catch (error) {
      toast.error('Document generation failed.', { id: toastId });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownloadPdf = async () => {
    const payload = { title, author, subject, keywords, content, fontFamily, fontSize, footerText };
    const success = await documentService.downloadPdf(payload);
    if (success) toast.success('Downloaded PDF Document!');
  };

  const handleDownloadDocx = async () => {
    const payload = { title, author, subject, keywords, content, fontFamily, fontSize, footerText };
    const success = await documentService.downloadDocx(payload);
    if (success) toast.success('Downloaded Microsoft Word (.docx) Document!');
  };

  return (
    <PageContainer>
      {/* Top Header Banner Card */}
      <div className="bg-[#1B1E25] border border-white/10 rounded-3xl p-6 sm:p-8 shadow-2xl flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="space-y-1.5">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[rgba(232,180,93,0.14)] border border-[#E8B45D]/30 text-[#E8B45D] text-xs font-bold">
            <FileText className="w-3.5 h-3.5" />
            AI DOCUMENT GENERATOR AGENT
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-white flex items-center gap-3">
            <FileText className="w-7 h-7 text-[#E8B45D]" />
            <span>AI Document Generator</span>
          </h1>
          <p className="text-[#C6C9D1] text-xs sm:text-sm max-w-2xl leading-relaxed font-normal">
            Create professional, downloadable PDF and Microsoft Word (.docx) documents from text or Markdown files with optional Gemini 2.5 Flash content enhancements.
          </p>
        </div>

        <div className="flex items-center gap-3 shrink-0">
          <button
            onClick={() => setActiveTab(activeTab === 'editor' ? 'preview' : 'editor')}
            className="btn-secondary px-4 py-2.5 text-xs flex items-center gap-2"
          >
            <Eye className="w-4 h-4 text-[#E8B45D]" />
            <span>{activeTab === 'editor' ? 'View Live Preview' : 'Edit Document'}</span>
          </button>

          <button
            onClick={handleGenerateDocuments}
            disabled={isGenerating}
            className="btn-primary px-5 py-2.5 text-xs flex items-center gap-2 shadow-md text-[#14161B]"
          >
            {isGenerating ? <RefreshCw className="w-4 h-4 animate-spin text-[#14161B]" /> : <Sparkles className="w-4 h-4 text-[#14161B]" />}
            <span>Generate Document</span>
          </button>
        </div>
      </div>

      {/* Main 12-Col Layout: Editor/Settings (7 Cols) & Live Preview (5 Cols) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Left 7 Columns: Input & Styling */}
        <div className="lg:col-span-7 space-y-6">
          
          {/* File Upload Dropzone - Dark Work Surface */}
          <div className="dark-work-surface p-5 flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <span className="p-2.5 rounded-xl bg-blue-500/20 text-blue-400 border border-blue-500/30">
                <Upload className="w-5 h-5" />
              </span>
              <div>
                <h4 className="text-xs font-bold text-white">Import Existing Document</h4>
                <p className="text-[11px] text-slate-400">Upload Text (.txt) or Markdown (.md) files</p>
              </div>
            </div>

            <label className="px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold cursor-pointer transition shadow-md">
              Browse .txt / .md File
              <input type="file" accept=".txt,.md" onChange={handleFileUpload} className="hidden" />
            </label>
          </div>

          {/* Text Content Editor Card - Dark Work Surface */}
          <div className="dark-work-surface p-6 space-y-4">
            <div className="flex items-center justify-between border-b border-white/10 pb-3">
              <label className="text-xs font-bold text-white flex items-center gap-2">
                <Edit3 className="w-4 h-4 text-[#5B5FEF]" /> Document Content Editor (Markdown Supported)
              </label>
              <span className="text-[11px] text-slate-400 font-mono">
                {content.length} characters | {content.split(/\s+/).filter(Boolean).length} words
              </span>
            </div>

            <textarea
              value={content}
              onChange={(e) => setContent(e.target.value)}
              rows={12}
              placeholder="Type or paste your document content here (supports Markdown headings #, lists -, and bold **text**)..."
              className="w-full p-4 rounded-2xl bg-[#222937] border border-white/10 text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-[#5B5FEF] font-mono leading-relaxed resize-none"
            />
          </div>

          {/* Gemini 2.5 Flash AI Enhancements Panel - Dark Work Surface */}
          <div className="dark-work-surface p-6 space-y-4">
            <div className="flex items-center justify-between border-b border-white/10 pb-3">
              <div className="flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-amber-400" />
                <h3 className="text-xs font-bold text-white uppercase tracking-wider">
                  Optional AI Content Enhancements (Gemini 2.5 Flash)
                </h3>
              </div>
              <span className="text-[10px] text-slate-400 font-mono">Only executed on click</span>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2.5">
              {enhancementOptions.map(opt => (
                <button
                  key={opt.id}
                  onClick={() => handleEnhanceWithGemini(opt.id)}
                  disabled={isEnhancing}
                  className={`p-2.5 rounded-xl border text-left transition flex flex-col justify-between ${selectedEnhancement === opt.id ? 'bg-amber-500/20 text-amber-200 border-amber-500/40 shadow-inner' : 'bg-slate-950/70 border-slate-800 text-slate-300 hover:border-blue-500/40'}`}
                >
                  <span className="text-xs font-bold flex items-center justify-between">
                    {opt.label}
                    {selectedEnhancement === opt.id && <Check className="w-3 h-3 text-amber-400" />}
                  </span>
                  <span className="text-[10px] text-slate-500 line-clamp-1 mt-1">{opt.desc}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Document Settings & Configuration */}
          <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-5 shadow-xl space-y-4">
            <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider flex items-center gap-2">
              <Settings className="w-4 h-4 text-blue-400" /> Document Configuration & Typography
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="space-y-1">
                <label className="text-[11px] font-semibold text-slate-400">Document Title</label>
                <input
                  type="text"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  className="w-full px-3 py-2 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-100"
                />
              </div>

              <div className="space-y-1">
                <label className="text-[11px] font-semibold text-slate-400">Author Name</label>
                <input
                  type="text"
                  value={author}
                  onChange={(e) => setAuthor(e.target.value)}
                  className="w-full px-3 py-2 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-100"
                />
              </div>

              <div className="space-y-1">
                <label className="text-[11px] font-semibold text-slate-400">Font Family</label>
                <select
                  value={fontFamily}
                  onChange={(e) => setFontFamily(e.target.value)}
                  className="w-full px-3 py-2 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-100"
                >
                  <option value="Helvetica">Helvetica (Standard Clean)</option>
                  <option value="Times New Roman">Times New Roman (Academic)</option>
                  <option value="Arial">Arial (Modern Sans)</option>
                  <option value="Courier">Courier (Monospace)</option>
                </select>
              </div>

              <div className="space-y-1">
                <label className="text-[11px] font-semibold text-slate-400">Font Size</label>
                <select
                  value={fontSize}
                  onChange={(e) => setFontSize(Number(e.target.value))}
                  className="w-full px-3 py-2 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-100"
                >
                  <option value={10}>10 pt (Small)</option>
                  <option value={12}>12 pt (Standard)</option>
                  <option value={14}>14 pt (Large)</option>
                </select>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
              <div className="space-y-1">
                <label className="text-[11px] font-semibold text-slate-400">Header Text</label>
                <input
                  type="text"
                  value={headerText}
                  onChange={(e) => setHeaderText(e.target.value)}
                  className="w-full px-3 py-2 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-100"
                />
              </div>

              <div className="space-y-1">
                <label className="text-[11px] font-semibold text-slate-400">Footer Text</label>
                <input
                  type="text"
                  value={footerText}
                  onChange={(e) => setFooterText(e.target.value)}
                  className="w-full px-3 py-2 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-100"
                />
              </div>
            </div>
          </div>

        </div>

        {/* Right 5 Columns: Live Document Preview & Download Actions */}
        <div className="lg:col-span-5 space-y-6">
          
          {/* Download Action Cards */}
          <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-4">
            <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider flex items-center gap-2">
              <Download className="w-4 h-4 text-emerald-400" /> Download Document Formats
            </h3>

            <div className="grid grid-cols-2 gap-3">
              <button
                onClick={handleDownloadPdf}
                className="p-4 rounded-xl bg-gradient-to-r from-rose-950/80 to-slate-900 border border-rose-500/30 hover:border-rose-500/60 text-rose-300 transition text-left space-y-2 group hover:scale-[1.02]"
              >
                <div className="flex items-center justify-between">
                  <span className="text-xs font-black text-rose-400 uppercase">PDF File</span>
                  <Download className="w-4 h-4 group-hover:translate-y-0.5 transition" />
                </div>
                <p className="text-[10px] text-slate-400">Standard printable PDF (.pdf)</p>
              </button>

              <button
                onClick={handleDownloadDocx}
                className="p-4 rounded-xl bg-gradient-to-r from-blue-950/80 to-slate-900 border border-blue-500/30 hover:border-blue-500/60 text-blue-300 transition text-left space-y-2 group hover:scale-[1.02]"
              >
                <div className="flex items-center justify-between">
                  <span className="text-xs font-black text-blue-400 uppercase">Word Doc</span>
                  <Download className="w-4 h-4 group-hover:translate-y-0.5 transition" />
                </div>
                <p className="text-[10px] text-slate-400">Editable Open XML (.docx)</p>
              </button>
            </div>
          </div>

          {/* Real-time Document Preview Sheet */}
          <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800">
              <div className="flex items-center gap-2">
                <Eye className="w-4 h-4 text-blue-400" />
                <h3 className="text-xs font-bold text-white uppercase tracking-wider">
                  Live Real-time Preview
                </h3>
              </div>
              <span className="text-[10px] text-slate-500 font-mono">Rendered Preview</span>
            </div>

            {/* Document Sheet Visual */}
            <div className="bg-white text-slate-900 p-6 sm:p-8 rounded-xl shadow-2xl space-y-4 font-sans text-xs min-h-[480px] border border-slate-300 overflow-y-auto max-h-[600px]">
              
              {/* Document Header */}
              {headerText && (
                <div className="text-[10px] font-bold uppercase text-slate-400 border-b border-slate-200 pb-2 mb-4">
                  {headerText}
                </div>
              )}

              {/* Document Title & Author Header */}
              <div className="space-y-1 pb-3 border-b border-slate-200">
                <h1 className="text-lg font-extrabold text-slate-900 leading-tight">
                  {title || 'Untitled Document'}
                </h1>
                <div className="text-[11px] text-slate-500 flex items-center justify-between">
                  <span>Author: {author || 'TaskPilot AI User'}</span>
                  <span>Date: {new Date().toLocaleDateString()}</span>
                </div>
              </div>

              {/* Body Content */}
              <div className="space-y-3 leading-relaxed whitespace-pre-wrap font-sans text-slate-800">
                {content ? (
                  content.split('\n').map((line, idx) => {
                    if (line.startsWith('# ')) {
                      return <h2 key={idx} className="text-sm font-bold text-slate-900 pt-2 border-b border-slate-100">{line.replace('# ', '')}</h2>;
                    }
                    if (line.startsWith('## ')) {
                      return <h3 key={idx} className="text-xs font-bold text-slate-800 pt-1">{line.replace('## ', '')}</h3>;
                    }
                    if (line.startsWith('- ') || line.startsWith('* ')) {
                      return <li key={idx} className="ml-4 list-disc text-slate-700">{line.replace(/^[-*]\s*/, '')}</li>;
                    }
                    return <p key={idx}>{line}</p>;
                  })
                ) : (
                  <p className="text-slate-400 italic">No content typed yet. Type or paste content on the left pane to preview...</p>
                )}
              </div>

              {/* Document Footer */}
              <div className="pt-6 border-t border-slate-200 mt-6 text-[10px] text-slate-400 flex items-center justify-between">
                <span>{footerText}</span>
                <span>Page 1 of 1</span>
              </div>

            </div>
          </div>

        </div>

      </div>

    </PageContainer>
  );
};

export default DocumentGenerator;
