/**
 * Data Transfer Object representing document generation configuration and content.
 */
export class DocumentDTO {
  constructor({
    title = 'Untitled Document',
    author = 'TaskPilot AI User',
    subject = '',
    keywords = '',
    content = '',
    fontFamily = 'Helvetica',
    fontSize = 12,
    pageSize = 'A4',
    orientation = 'portrait',
    margins = 'normal',
    headerText = '',
    footerText = 'Generated by TaskPilot AI',
    includePageNumbers = true,
    textAlignment = 'left',
    enhancementType = null
  }) {
    this.title = title;
    this.author = author;
    this.subject = subject;
    this.keywords = keywords;
    this.content = content;
    this.fontFamily = fontFamily;
    this.fontSize = fontSize;
    this.pageSize = pageSize;
    this.orientation = orientation;
    this.margins = margins;
    this.headerText = headerText;
    this.footerText = footerText;
    this.includePageNumbers = includePageNumbers;
    this.textAlignment = textAlignment;
    this.enhancementType = enhancementType;
  }
}

export default DocumentDTO;
