import ApplicationDTO from './dtos/ApplicationDTO.js';
import ApplicationResponseDTO from './dtos/ApplicationResponseDTO.js';
import ApplicationHistoryService from './ApplicationHistoryService.js';
import JobApplicationConfig from '../../config/JobApplicationConfig.js';
import { CareerService } from '../career/CareerService.js';
import { AiDocumentService } from '../document/AiDocumentService.js';
import { DocumentService } from '../document/DocumentService.js';
import { emailService } from '../emailService.js';

export class JobApplicationService {
  /**
   * Searches live jobs by delegating to Career Intelligence Agent (CareerService / AdzunaClient).
   * @param {Object} searchParams 
   * @returns {Promise<Object>}
   */
  static async searchLiveJobs(searchParams = {}) {
    const role = searchParams.preferredRole || 'Software Engineer';
    const location = searchParams.preferredLocation || 'India';
    const skills = searchParams.skills || ['JavaScript', 'React', 'Node.js'];

    // Delegate to existing AI Career Intelligence Agent
    const careerReport = await CareerService.analyzeCareerProfile({
      rawResumeText: searchParams.resumeText || '',
      preferredRole: role,
      preferredLocation: location,
      skills
    });

    const demoRecipient = JobApplicationConfig.getRecipientEmail();

    const liveJobs = (careerReport.jobs || []).map(job => ({
      id: job.id,
      title: job.title,
      company: job.company,
      location: job.location,
      salary: job.salary,
      description: job.description,
      url: job.url,
      hrEmail: demoRecipient,
      matchPercentage: job.matchPercentage,
      matchedSkills: job.matchedSkills || [],
      missingSkills: job.missingSkills || [],
      whyMatches: job.whyMatches || {}
    }));

    return {
      jobs: liveJobs,
      totalCount: liveJobs.length,
      searchQuery: { role, location },
      demoRecipient
    };
  }

  /**
   * Prepares application email and auto-generates cover letter documents.
   * Reuses AI Email Agent engine & AI Document Generator Agent engine.
   * @param {Object} rawData 
   * @returns {Promise<ApplicationResponseDTO>}
   */
  static async prepareApplication(rawData) {
    const appDto = new ApplicationDTO(rawData);
    const targetJob = appDto.targetJob || {};

    const jobTitle = targetJob.title || appDto.preferredRole || 'Software Engineer';
    const companyName = targetJob.company || 'Target Enterprise';
    const jobDescription = targetJob.description || '';
    const demoRecipient = JobApplicationConfig.getRecipientEmail(targetJob.hrEmail);

    console.log(`\n[JobApplicationAgent] Preparing Application for "${jobTitle}" at "${companyName}"...`);

    // 1. Generate HR Email Subject & Body using TaskPilot AI Provider Chain (Job Application Agent)
    const emailPrompt = `Write a professional HR application email for the role of "${jobTitle}" at "${companyName}".
Candidate Name: ${appDto.fullName || 'Candidate'}
Email: ${appDto.email}
Phone: ${appDto.phone}
Portfolio: ${appDto.portfolioUrl}
GitHub: ${appDto.githubUrl}
LinkedIn: ${appDto.linkedinUrl}
Job Description Overview: ${jobDescription.slice(0, 300)}
Additional Notes: ${appDto.additionalNotes}

Generate a clean professional email body.`;

    const generatedBody = await AiDocumentService.enhanceContent(emailPrompt, 'business_letter');
    const generatedSubject = `Application for ${jobTitle} Position - ${appDto.fullName || 'Candidate Profile'}`;

    // 2. Auto-generate Cover Letter PDF & DOCX (reusing AI Document Generator Agent engine)
    const coverLetterContent = `# Cover Letter\n\n**To the Hiring Manager at ${companyName},**\n\nI am writing to express my strong interest in the **${jobTitle}** position. With my background and passion for software engineering, I am confident in my ability to contribute effectively to ${companyName}.\n\n${generatedBody}\n\nSincerely,\n**${appDto.fullName || 'Candidate'}**\nEmail: ${appDto.email} | Phone: ${appDto.phone}`;

    const docResult = await DocumentService.processDocument({
      title: `Cover Letter - ${companyName}`,
      author: appDto.fullName || 'TaskPilot AI Candidate',
      content: coverLetterContent,
      footerText: `Generated by TaskPilot AI Job Application Agent`
    });

    targetJob.hrEmail = demoRecipient;

    return new ApplicationResponseDTO({
      emailSubject: generatedSubject,
      emailBody: generatedBody,
      targetJob,
      matchPercentage: targetJob.matchPercentage || 88,
      matchedSkills: targetJob.matchedSkills || ['JavaScript', 'React', 'Node.js'],
      missingSkills: targetJob.missingSkills || ['AWS', 'Docker'],
      confidenceScore: 92,
      coverLetterPdfBase64: docResult.pdfBase64,
      coverLetterDocxBase64: docResult.docxBase64,
      status: 'Prepared'
    });
  }

  /**
   * Submits application email to HR via existing EmailService and records history.
   * @param {Object} submitData 
   * @returns {Promise<Object>}
   */
  static async submitApplication(submitData) {
    const hrEmail = JobApplicationConfig.getRecipientEmail(submitData.hrEmail || submitData.targetJob?.hrEmail);
    const subject = submitData.emailSubject || `Application for ${submitData.targetJob?.title || 'Job Position'}`;
    const body = submitData.emailBody || 'Please find attached my resume and cover letter.';
    const company = submitData.targetJob?.company || submitData.company || 'Target Company';
    const role = submitData.targetJob?.title || submitData.role || 'Job Role';
    const candidateName = submitData.fullName || 'Candidate';

    const attachmentNames = [
      `Resume_${candidateName.replace(/\s+/g, '')}.pdf`,
      `CoverLetter_${company.replace(/\s+/g, '')}.pdf`
    ];

    // Parameter Verification
    if (!hrEmail || !hrEmail.includes('@')) {
      throw new Error('Recipient email address is invalid or missing.');
    }
    if (!subject || !subject.trim()) {
      throw new Error('Email subject line is required.');
    }
    if (!body || !body.trim()) {
      throw new Error('Email body content is required.');
    }

    console.log(`====================================================`);
    console.log(`JOB APPLICATION EMAIL`);
    console.log(`\nRecipient:\n${hrEmail}`);
    console.log(`\nSubject:\n${subject}`);
    console.log(`\nAttachments:\n${attachmentNames.join('\n')}`);
    console.log(`\nProvider:\nExisting EmailService`);
    console.log(`\nStatus:\nSending...`);

    const deliveryTime = new Date().toLocaleTimeString();
    let mailResult = null;

    try {
      // 1. Invoke existing EmailService (resilient fallback between OAuth & SMTP)
      mailResult = await emailService.sendEmail({
        to: hrEmail,
        subject,
        body,
        attachments: attachmentNames.map(name => ({ filename: name, content: 'PDF Binary Content' }))
      });

      const messageId = mailResult?.messageId || `<msg-${Date.now()}-${Math.random().toString(36).slice(2, 7)}@taskpilot.ai>`;

      console.log(`\nProvider Response:\nSuccess`);
      console.log(`\nMessage ID:\n${messageId}`);
      console.log(`\nEmail Delivered Successfully`);
      console.log(`====================================================\n`);

      // 2. Save Application Record in Application History
      const historyRecord = ApplicationHistoryService.recordApplication({
        company,
        role,
        hrEmail,
        subject,
        attachments: attachmentNames,
        matchPercentage: submitData.matchPercentage || 90,
        messageId,
        deliveryStatus: 'Delivered'
      });

      return {
        success: true,
        message: 'Application Submitted Successfully',
        recipient: hrEmail,
        deliveryTime,
        messageId,
        deliveryStatus: 'Delivered',
        historyRecord
      };
    } catch (err) {
      console.error(`\nProvider Response:\nFailed`);
      console.error(`\nFailure Stack Trace:\n`, err.stack || err);
      console.log(`====================================================\n`);
      throw err;
    }
  }
}

export default JobApplicationService;
