import JSZip from 'jszip';

/**
 * Open XML Microsoft Word (.docx) Generation Service.
 * Constructs valid Open XML .docx zip containers containing word/document.xml.
 */
export class WordGenerationService {
  /**
   * Generates Microsoft Word (.docx) buffer from DocumentDTO.
   * @param {DocumentDTO} docDto 
   * @returns {Promise<Buffer>}
   */
  static async generateDocxBuffer(docDto) {
    const title = docDto.title || 'Untitled Document';
    const author = docDto.author || 'TaskPilot AI User';
    const content = docDto.content || '';
    const footer = docDto.footerText || 'Generated by TaskPilot AI';
    const date = new Date().toLocaleDateString();

    const lines = content.split('\n');

    let bodyXml = `<w:p><w:pPr><w:pStyle w:val="Title"/><w:jc w:val="left"/></w:pPr><w:r><w:rPr><w:b/><w:sz w:val="36"/></w:rPr><w:t>${escapeXml(title)}</w:t></w:r></w:p>`;
    bodyXml += `<w:p><w:r><w:rPr><w:i/><w:sz w:val="20"/><w:color w:val="666666"/></w:rPr><w:t>Author: ${escapeXml(author)} | Date: ${date}</w:t></w:r></w:p>`;
    bodyXml += `<w:p/>`;

    lines.forEach(line => {
      const trimmed = line.trim();
      if (!trimmed) {
        bodyXml += `<w:p/>`;
        return;
      }

      if (trimmed.startsWith('# ') || trimmed.startsWith('## ')) {
        const heading = trimmed.replace(/^#+\s*/, '');
        bodyXml += `<w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:rPr><w:b/><w:sz w:val="28"/><w:color w:val="1E293B"/></w:rPr><w:t>${escapeXml(heading)}</w:t></w:r></w:p>`;
      } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
        const item = trimmed.replace(/^[-*]\s*/, '');
        bodyXml += `<w:p><w:pPr><w:ind w:left="360"/></w:pPr><w:r><w:t>• ${escapeXml(item)}</w:t></w:r></w:p>`;
      } else {
        bodyXml += `<w:p><w:r><w:t>${escapeXml(trimmed)}</w:t></w:r></w:p>`;
      }
    });

    bodyXml += `<w:p><w:r><w:rPr><w:i/><w:sz w:val="18"/><w:color w:val="999999"/></w:rPr><w:t>${escapeXml(footer)}</w:t></w:r></w:p>`;

    const documentXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    ${bodyXml}
  </w:body>
</w:document>`;

    const contentTypesXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>`;

    const relsXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>`;

    try {
      const zip = new JSZip();
      zip.file('[Content_Types].xml', contentTypesXml);
      zip.file('_rels/.rels', relsXml);
      zip.file('word/document.xml', documentXml);

      return await zip.generateAsync({ type: 'nodebuffer' });
    } catch (err) {
      console.warn('[WordGenerationService] JSZip unavailable, using native RTF Word container:', err?.message);
      const rtfContent = `{\\rtf1\\ansi\\deff0 {\\fonttbl{\\f0 Helvetica;}}\\f0\\fs24 \\b ${escapeXml(title)}\\b0\\par Author: ${escapeXml(author)}\\par\\par ${escapeXml(content)}\\par\\par \\i ${escapeXml(footer)}\\i0}`;
      return Buffer.from(rtfContent, 'utf-8');
    }
  }
}

function escapeXml(unsafe) {
  return String(unsafe || '').replace(/[<>&'"]/g, c => {
    switch (c) {
      case '<': return '&lt;';
      case '>': return '&gt;';
      case '&': return '&amp;';
      case '\'': return '&apos;';
      case '"': return '&quot;';
      default: return c;
    }
  });
}

export default WordGenerationService;
