import { BaseProvider } from './BaseProvider.js';

export class MockProvider extends BaseProvider {
  constructor(config = {}) {
    super({ name: 'MockProvider', model: 'mock-v1', ...config });
  }

  async generateText(prompt, options = {}) {
    return `[MockProvider Response] Text generated for: "${prompt}"`;
  }

  async generateStructuredResponse(prompt, schema = {}, options = {}) {
    return { mock: true, prompt, schema };
  }

  async generateImage(prompt, options = {}) {
    return {
      error: 'Image generation is not yet supported by the configured provider.',
      message: 'Image generation is not yet supported by the configured provider.'
    };
  }

  async generateDiagram(prompt, options = {}) {
    return `graph TD;\n  A[Start ${prompt}] --> B[Analyze Context];\n  B --> C[Generate Response];`;
  }

  async generateMindMap(prompt, options = {}) {
    return `# ${prompt}\n- Core Concepts\n  - Subtopic 1\n  - Subtopic 2`;
  }

  async generateQuiz(topic, options = {}) {
    return [
      { question: `Sample quiz question on ${topic}?`, options: ['Option A', 'Option B', 'Option C', 'Option D'], answer: 0 }
    ];
  }

  async generateFlashcards(topic, options = {}) {
    return [
      { front: `What is ${topic}?`, back: `Mock definition of ${topic}` }
    ];
  }

  async summarize(text, options = {}) {
    return `[Mock Summary]: ${text.slice(0, 100)}...`;
  }

  async explain(topic, options = {}) {
    return `[Mock Explanation]: Comprehensive explanation of ${topic}.`;
  }

  async explainTopic(topic, options = {}) {
    if (typeof topic === 'string' && (topic.startsWith('Describe') || topic.length > 50)) {
      return `### 🎨 Visual Breakdown & Analysis\n\n- **Subject Focus**: Detailed rendering based on original prompt instructions.\n- **Artistic Style & Composition**: Rich atmospheric balance with high dynamic depth, structured color palette, and dramatic focal points.\n- **Lighting & Atmosphere**: Carefully balanced volumetric lighting with vibrant accent highlights and deep shadows.`;
    }
    return `Detailed visual breakdown and conceptual explanation of ${topic}.`;
  }

  async generateNotes(topic, options = {}) {
    return `[Mock Notes]: Study notes for "${topic}".\n\n- Key concept 1\n- Key concept 2\n- Key concept 3`;
  }

  async generateStudyPlan(topic, options = {}) {
    return { topic, duration: '4 Weeks', weeklyPlan: [{ week: 1, title: 'Foundations', goals: ['Learn basics'], dailyHours: 2 }] };
  }

  async generateRoadmap(goal, options = {}) {
    const planText = `# 📌 AI-Generated Roadmap: ${goal}

## 🎯 Goal Overview
Your goal is to achieve: "${goal}". Based on your configured schedule and intensity, here is a structured execution plan.

---

## 🗺️ Phase 1 — Foundations & Prerequisites (Week 1-2)
- Understand core fundamentals and set up your learning environment
- Study key theoretical concepts with 2-3 hours of daily focused sessions
- Complete beginner-level exercises and note any weak areas
- **Milestone**: Pass a self-assessment quiz on foundational topics

## 🚀 Phase 2 — Core Implementation (Week 3-4)
- Dive into intermediate topics, building real-world mini-projects
- Solve 2-3 practice problems per day, focusing on pattern recognition
- Begin a project portfolio showcasing key skills learned
- **Milestone**: Complete one functional project and document it

## 🏆 Phase 3 — Advanced Practice & Mastery (Week 5-6)
- Tackle advanced concepts, mock tests, and full-scale project builds
- Focus on weak spots identified during Phase 1
- Review and revise notes; participate in peer reviews
- **Milestone**: Complete a capstone project or mock assessment

---

## 📅 Daily Schedule Template
| Time Slot       | Activity                          |
|-----------------|-----------------------------------|
| 08:00 - 09:00  | Review previous day's notes       |
| 09:00 - 11:00  | New topic deep-dive               |
| 11:00 - 12:00  | Hands-on coding / exercises       |
| 14:00 - 15:30  | Practice problems / mock tests    |
| 20:00 - 21:00  | Evening revision & flashcards     |

---

## ✅ Recommended Resources
- Video Courses: YouTube Channels (freeCodeCamp, Traversy Media)
- Books: "Clean Code" by Robert Martin; "The Pragmatic Programmer"
- Practice Platforms: LeetCode, HackerRank, CodeForces
- Community: Stack Overflow, Reddit communities, Discord study groups

---

*Generated by TaskPilot AI Planner Agent. Adapt this roadmap according to your pace.*`;

    return {
      goal,
      response: planText,
      milestones: [
        { step: 1, title: 'Foundations & Prerequisites', description: `Master core concepts for: ${goal}`, estimatedDays: 14, recommendedResources: ['freeCodeCamp', 'YouTube tutorials'] },
        { step: 2, title: 'Core Implementation', description: 'Build intermediate modules and complete practice exercises', estimatedDays: 14, recommendedResources: ['LeetCode', 'HackerRank'] },
        { step: 3, title: 'Advanced Practice & Mastery', description: 'Deploy capstone projects and execute mock assessments', estimatedDays: 14, recommendedResources: ['GitHub Portfolio', 'Mock Interview Platforms'] }
      ]
    };
  }

  async generateTasks(goal, options = {}) {
    return [{ title: `Task for ${goal}`, category: 'Learning', priority: 'High', estimatedMinutes: 30, xpReward: 20 }];
  }

  async generateInterviewQuestions(topic, options = {}) {
    return [{ question: `What is ${topic}?`, difficulty: 'Medium', modelAnswer: `${topic} is...`, keyKeywords: [topic] }];
  }

  async generateMermaidDiagram(topic, options = {}) {
    return `graph TD;\n  A[${topic}] --> B[Core Concepts];\n  B --> C[Applications];`;
  }

  async generateMindMapJSON(topic, options = {}) {
    return { id: 'root', label: topic, children: [{ id: 'sub-1', label: 'Core Concepts', children: [] }] };
  }

  async chat(messages = [], options = {}) {
    const lastMsg = messages[messages.length - 1]?.content || 'Hello';
    return `[Mock AI Chat]: Responding to "${lastMsg}"`;
  }
}

export default MockProvider;
